CREATE TABLE "STUDY_LOG"(
    "MEM_ID" VARCHAR2(50),
    "STU_CODE" CHAR(10),
    "COMPLETED" CHAR(1),
    "REG_DATE" DATE,
    FOREIGN KEY (MEM_ID) REFERENCES "MEMBER"(ID),
    FOREIGN KEY (STU_CODE) REFERENCES "STUDY_CONTENTS"(CODE)
);

--- QUESTION_LIST 뷰.
CREATE OR REPLACE VIEW VW_STUDY_LOG_CALCULATION AS
    SELECT STU_CODE, MEM_ID, COUNT(*) AS STU_COUNT , TRUNC((SYSDATE - MAX(REG_DATE))*(60*60)) AS ELAPSED_TIME
    FROM STUDY_LOG
    GROUP BY STU_CODE, MEM_ID
    ORDER BY ELAPSED_TIME;

drop table study_log;
DROP VIEW VW_STUDY_LOG_CALCULATION;

commit;




-- STUDY LOG를 삽입하는 부분 
INSERT INTO STUDY_LOG(MEM_ID,STU_CODE, COMPLETED, REG_DATE) VALUES ('tp1130', '010101C001', 'O', SYSDATE);
INSERT INTO STUDY_LOG(MEM_ID,STU_CODE,REG_DATE) VALUES ('tp1130', '010101C002', SYSDATE);
INSERT INTO STUDY_LOG(MEM_ID,STU_CODE,REG_DATE) VALUES ('tp1130', '010101C001', SYSDATE);

---- 새로운 연습
SELECT *
FROM VW_STUDY_LOG_CALCULATION
WHERE MEM_ID = 'tp1130';

-- 학습별 학습한 횟수, 경과한 시간(분) 조회
SELECT STU_CODE, MEM_ID, COUNT(*) AS CNT , TRUNC((SYSDATE - MAX(REG_DATE))*(60*60)) AS ELAPSED_TIME
FROM STUDY_LOG
GROUP BY STU_CODE, MEM_ID
ORDER BY ELAPSED_TIME;


-- 남은 학습의 개수를 조회
SELECT CO_CODE, count(*) AS REMANING_STUDY_COUNT
FROM VW_STUDY_CONTENTS_LIST
WHERE CODE NOT IN (
    SELECT DISTINCT(STU_CODE) 
    FROM STUDY_LOG
    WHERE MEM_ID='tp1130'
    )
GROUP BY CO_CODE ;

--학습별 학습한 횟수, 마지막 공부한 날짜 조회
SELECT STU_CODE, COUNT(*) AS CNT , MAX(REG_DATE) AS LAST_DATE
FROM STUDY_LOG
GROUP BY STU_CODE;

-- 가장 최근 공부한 STU_CODE 조회
SELECT STU_CODE, title
FROM STUDY_LOG stl, vw_study_contents_list vsc
WHERE stl.STU_CODE = vsc.CODE AND CO_CODE='C01' AND MEM_ID='tp1130'
    AND stl.REG_DATE = (
    SELECT MAX(stl.REG_DATE)
    FROM STUDY_LOG stl, vw_study_contents_list vsc
    WHERE stl.STU_CODE = vsc.CODE AND vsc.CO_CODE='C01' AND MEM_ID='tp1130');
