-- MEMBER
CREATE TABLE "MEMBER" (
   "ID"       VARCHAR2(50) PRIMARY KEY,
   "EMAIL"    VARCHAR2(100),
   "PASSWORD" VARCHAR2(50)
);

INSERT INTO MEMBER (ID, EMAIL, PASSWORD) VALUES ('tp1130', 'thinpig1130@gamail.com', 'qwer1234!!');


-- CODE C99 과정은 99개까지 등록가능.
CREATE TABLE "COURSE" (
   "CODE" CHAR(3) PRIMARY KEY, 
   "NAME" VARCHAR2(150) 
);

INSERT INTO Course (CODE, NAME)	VALUES ('C01', '정보처리기사 필기');
INSERT INTO Course (CODE, NAME)	VALUES ('C02', '정보처리기사 실기');


-- CODE 99C12 한 과정당 카테고리은 99개까지 등록가능.
CREATE TABLE "CATEGORY" (
   "CODE"    CHAR(5) PRIMARY KEY,
   "NAME"    VARCHAR2(150) ,
   "CO_CODE" CHAR(3) NOT NULL,
   FOREIGN KEY (CO_CODE) REFERENCES "COURSE"(CODE)
);

INSERT INTO CATEGORY (CODE, NAME, CO_CODE) VALUES ('01C01', '응용소프트웨어 엔지니어링', 'C01');


-- CODE 9912C66 한 카테고리당 작은카테고리 99개까지 등록가능.
CREATE TABLE "SUB_CATEGORY" (
   "CODE"    CHAR(7) PRIMARY KEY,
   "NAME"    VARCHAR2(150) ,
   "CA_CODE" CHAR(5) NOT NULL,
   FOREIGN KEY (CA_CODE) REFERENCES "CATEGORY"(CODE)
);

INSERT INTO SUB_CATEGORY (CODE, NAME, CA_CODE) VALUES ('0101C01', '응용소프트웨어 설계', '01C01');

-- CODE 991266C456 한 작은카테고리당 999개의 학습 모듈 등록가능.
CREATE TABLE "STUDY_CONTENTS" (
   "CODE"       CHAR(10) PRIMARY KEY,
   "IMPORTANCE" NUMBER(1),
   "TITLE"      VARCHAR2(150),
   "CONTENTS"   LONG,
   "REG_DATE"   DATE,
   "SUB_CODE"   CHAR(7) NOT NULL,
   FOREIGN KEY (SUB_CODE) REFERENCES "SUB_CATEGORY"(CODE)
);

--INSERT INTO STUDY_CONTENTS (CODE, IMPORTANCE, TITLE, CONTENTS, REG_DATE, SUB_CODE) VALUES (#{code}, #{importance}, #{title}, #{contents}, SYS_DATE, #{subCode})

-- CODE 991266456C100 한 학습모듈 당 주관식/객관식 합 999문제 등록 가능.
CREATE TABLE "M_QUESTION" (
   "CODE"       CHAR(13) PRIMARY KEY,
   "QUESTION"   VARCHAR2(1500),
   "STU_CODE"   CHAR(10) NOT NULL,
   FOREIGN KEY (STU_CODE) REFERENCES "STUDY_CONTENTS"(CODE)
);

-- CODE 991266456Q100 한 학습모듈 당 주관식/객관식 합 999문제 등록 가능.
CREATE TABLE "S_QUESTION" (
   "CODE"       CHAR(13) PRIMARY KEY,
   "QUESTION"   VARCHAR2(3000),
   "ANSWER"     VARCHAR2(1500),
   "STU_CODE"   CHAR(10) NOT NULL,
   FOREIGN KEY (STU_CODE) REFERENCES "STUDY_CONTENTS"(CODE)
);

CREATE TABLE "M_ANSWER" (
   "CODE"    NUMERIC,
   "Q_CODE"  CHAR(8),
   "ANSWER"  VARCHAR2(150),
   "CORRECT" CHAR(1),
   PRIMARY KEY (CODE,Q_CODE), 
   FOREIGN KEY (Q_CODE) REFERENCES "M_QUESTION"(CODE)
);

DROP TABLE MEMBER;
DROP TABLE COURSE;
DROP TABLE CATEGORY;
DROP TABLE SUB_CATEGORY;
DROP TABLE STUDY_CONTENTS;
DROP TABLE M_QUESTION;
DROP TABLE S_QUESTION;
DROP TABLE M_ANSWER;

--- STUDY_CONTNETS 목록 전부 조회 // 추가 할 것 등록된 문제 수
SELECT cor.CODE, cor.NAME, cat.CODE, cat.NAME, sub.CODE, sub.NAME, stu.CODE, stu.TITLE 
FROM STUDY_CONTENTS stu, SUB_CATEGORY sub, CATEGORY cat, COURSE cor
WHERE stu.SUB_CODE = sub.CODE AND sub.CA_CODE = cat.CODE AND cat.CO_CODE = cor.CODE ;


