/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2020-09-17 05:49:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class datetimepicker_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"./assets/img/apple-icon.png\">\r\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"./assets/img/favicon.png\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("  <title>\r\n");
      out.write("    base페이지이름 in Code Bridge </> \r\n");
      out.write("  </title>\r\n");
      out.write("  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />\r\n");
      out.write("  <!--     Fonts and icons     -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\r\n");
      out.write("  <!-- CSS Files -->\r\n");
      out.write("  <link href=\"/resources/assets_home/css/material-kit.css?v=2.0.7\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- CSS Just for demo purpose, don't include it in your project -->\r\n");
      out.write("  <link href=\"/resources/assets_home/demo/demo.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"profile-page sidebar-collapse\">\r\n");
      out.write("  <!-- 로그인 폼 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"\">\r\n");
      out.write("    <div class=\"modal-dialog modal-login\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"card card-signup card-plain\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <div class=\"card-header card-header-primary text-center\">\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><i class=\"material-icons\">clear</i></button>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <h4 class=\"card-title\">Log in</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form class=\"form\" method=\"post\" action=\"/member/login\">\r\n");
      out.write("                  <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <div class=\"form-group bmd-form-group\">\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                              <span class=\"input-group-addon\">\r\n");
      out.write("                                  <i class=\"material-icons\">face</i>\r\n");
      out.write("                              </span>\r\n");
      out.write("                              <input type=\"text\" class=\"form-control\" placeholder=\" 아이디 입력\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"form-group bmd-form-group\">\r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                              <span class=\"input-group-addon\">\r\n");
      out.write("                                  <i class=\"material-icons\">lock_outline</i>\r\n");
      out.write("                              </span>\r\n");
      out.write("                              <input type=\"password\" placeholder=\"비밀번호 입력\" class=\"form-control\">\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"modal-footer justify-content-center\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary btn-link btn-wd btn-lg\">로그인</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<!--8.25재만수정끝-->\r\n");
      out.write("\r\n");
      out.write("  <!--상단 네비게이션 바-->\r\n");
      out.write("  <nav class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg bg-primary\" color-on-scroll=\"100\" id=\"sectionsNav\">\r\n");
      out.write("  <!--<nav class=\"navbar fixed-bottom navbar-expand-lg  bg-primary\">-->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"/home\">weLEarn &nbsp;&nbsp;&nbsp;  </a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("        <!-- 아이콘 바 -->\r\n");
      out.write("        <ul class=\"navbar-nav ml-auto\" role=\"tablist\">\r\n");
      out.write("          <!--\r\n");
      out.write("              color-classes: \"nav-pills-primary\", \"nav-pills-info\", \"nav-pills-success\", \"nav-pills-warning\",\"nav-pills-danger\"\r\n");
      out.write("          -->\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"javascript:;\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("              <i class=\"material-icons\">person_pin</i>&nbsp;&nbsp; STUDY\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"/user/status\">\r\n");
      out.write("                <i class=\"material-icons\">dashboard</i>&nbsp;&nbsp;학습현황\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"/user/study\">\r\n");
      out.write("                <i class=\"material-icons\">edit</i>&nbsp;&nbsp;학습하기\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"/user/testing\">\r\n");
      out.write("                <i class=\"material-icons\">rate_review</i>&nbsp;&nbsp;문제풀기\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"/user/review\">\r\n");
      out.write("                <i class=\"material-icons\">psychology</i>&nbsp;&nbsp;복습하기\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item dropdown\">\r\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"javascript:;\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("              <i class=\"material-icons\">face</i>&nbsp;&nbsp; Start\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"/member/logout\">로그아웃</a>\r\n");
      out.write("              <a class=\"dropdown-item\" data-toggle=\"modal\" data-target=\"#loginModal\">로그인</a>\r\n");
      out.write("              <a class=\"dropdown-item\" href=\"/member/joinform\">회원가입</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <div class=\"page-header header-filter clear-filter purple-filter\" data-parallax=\"true\" style=\"background-image: url('/resources/assets_home/img/bg2.jpg');\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-8 ml-auto mr-auto\">\r\n");
      out.write("          <div class=\"brand\">\r\n");
      out.write("            <h1>weLEarn</h1>\r\n");
      out.write("            <h3>배우고 익히는 좋은 습관</h3>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"main main-raised\">\r\n");
      out.write("    <div class=\"section section-basic\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <!-- 아이콘 바 -->\r\n");
      out.write("        <ul class=\"nav nav-pills nav-pills-icons\" role=\"tablist\">\r\n");
      out.write("          <!--\r\n");
      out.write("              color-classes: \"nav-pills-primary\", \"nav-pills-info\", \"nav-pills-success\", \"nav-pills-warning\",\"nav-pills-danger\"\r\n");
      out.write("          -->\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active\" href=\"#newface\" role=\"tab\" data-toggle=\"tab\">\r\n");
      out.write("                  <i class=\"material-icons\">emoji_people</i>\r\n");
      out.write("                  weLEarn\r\n");
      out.write("              </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#meeting\" role=\"tab\" data-toggle=\"tab\">\r\n");
      out.write("                  <i class=\"material-icons\">dashboard</i>\r\n");
      out.write("                  학습현황\r\n");
      out.write("              </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#veteran\" role=\"tab\" data-toggle=\"tab\">\r\n");
      out.write("                <i class=\"material-icons\">edit</i>\r\n");
      out.write("                학습하기\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#coding_q_and_a\" role=\"tab\" data-toggle=\"tab\">\r\n");
      out.write("                <i class=\"material-icons\">rate_review</i>\r\n");
      out.write("                문제풀기\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"#course\" role=\"tab\" data-toggle=\"tab\">\r\n");
      out.write("              <i class=\"material-icons\">psychology</i>\r\n");
      out.write("              복습하기\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- 아이콘 클릭시 !! -->\r\n");
      out.write("        <div class=\"tab-content tab-space\">\r\n");
      out.write("          <div class=\"tab-pane active\" id=\"newface\">\r\n");
      out.write("            집시(집안지은사람) > 정보를 등록한 사람 : 이주민  > 개인방만든사람 : 토착민 > 비법전수 1회 이상 : 지역유지 > 유명인사 (최근 3개월간 방문자 수 높으면) <br> \r\n");
      out.write("            <br><br>\r\n");
      out.write("            자기 자신에 등급에 맞는 정보 출력.\r\n");
      out.write("            <br><br>\r\n");
      out.write("            최근 가입한 사람의 목록 출력 (최근순)\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"tab-pane\" id=\"meeting\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-4\">\r\n");
      out.write("                  <div class=\"card\">\r\n");
      out.write("                      <div class=\"card-header card-header-primary\">\r\n");
      out.write("                        <div class=\"card-icon\">\r\n");
      out.write("                          <i class=\"material-icons\">groups</i>&nbsp;&nbsp;&nbsp; 세종시 폭풍 공감 모임\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"card-body\">\r\n");
      out.write("                          <h4 class=\"card-title\"> 일시 : 2020. 9. 10</h4>\r\n");
      out.write("                          프로그래머만 알아듣는 유머. 비유... \r\n");
      out.write("                          그리고 함께겪는 어려움과 기쁨을 함께하는 공감과 소통의 장에 초대합니다.\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                  <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-header card-header-primary\">\r\n");
      out.write("                          <div class=\"card-icon\">\r\n");
      out.write("                            <i class=\"material-icons\">groups</i>&nbsp;&nbsp;&nbsp; 세종시 폭풍 공감 모임\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <h4 class=\"card-title\"> 일시 : 2020. 9. 10</h4>\r\n");
      out.write("                            프로그래머만 알아듣는 유머. 비유... \r\n");
      out.write("                            그리고 함께겪는 어려움과 기쁨을 함께하는 공감과 소통의 장에 초대합니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                        <div class=\"card-header card-header-icon card-header-primary\">\r\n");
      out.write("                          <div class=\"card-icon\">\r\n");
      out.write("                            <i class=\"material-icons\">groups</i> &nbsp;&nbsp;&nbsp;모각코\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <h4 class=\"card-title\"> 일시 : 2020. 9. 10</h4>\r\n");
      out.write("                            프로그래머만 알아듣는 유머. 비유... \r\n");
      out.write("                            그리고 함께겪는 어려움과 기쁨을 함께하는 공감과 소통의 장에 초대합니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("          <div class=\"tab-pane\" id=\"veteran\">\r\n");
      out.write("            검색tab 입력 조건에 맞는 목록 검색 출력\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"exampleFormControlSelect1\">검색조건선택</label>\r\n");
      out.write("              <select class=\"form-control selectpicker\" data-style=\"btn btn-link\" id=\"exampleFormControlSelect1\">\r\n");
      out.write("                <option>등급</option>\r\n");
      out.write("                <option>이름</option>\r\n");
      out.write("                <option>제목</option>\r\n");
      out.write("                <option>기업</option>\r\n");
      out.write("                <option>등등</option>\r\n");
      out.write("              </select>\r\n");
      out.write("          </div>    \r\n");
      out.write("          <form>\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              <label for=\"search\">Search</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"search\" placeholder=\"검색어 입력(등급,이름,코딩문답제목,기업)\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary btn-round\">검색</button>\r\n");
      out.write("          </form>\r\n");
      out.write("           <!-- 등급,이름,코딩문답제목,기업 -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"tab-pane\" id=\"coding_q_and_a\">\r\n");
      out.write("            <div class=\"text-right\">\r\n");
      out.write("              <a href=\"base.html\" class=\"btn btn-primary btn-sm\">더보기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h3><small># IT</small></h3>\r\n");
      out.write("            <table class=\"table table-sm table-hover\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"col\">No</th>\r\n");
      out.write("                  <th scope=\"col\">질문</th>\r\n");
      out.write("                  <th scope=\"col\">분야</th>\r\n");
      out.write("                  <th scope=\"col\">조회수/댓글수</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">5</th>\r\n");
      out.write("                  <td>고수님들 쫌 도와주세요.</td>\r\n");
      out.write("                  <td>JAVA</td>\r\n");
      out.write("                  <td>10/0</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">4</th>\r\n");
      out.write("                  <td>고수님들 쫌 도와주세요.</td>\r\n");
      out.write("                  <td>JAVA</td>\r\n");
      out.write("                  <td>10/0</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">3</th>\r\n");
      out.write("                  <td>고수님들 쫌 도와주세요.</td>\r\n");
      out.write("                  <td>JAVA</td>\r\n");
      out.write("                  <td>10/0</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">2</th>\r\n");
      out.write("                  <td>이 에러는 왜 날까요? 이방법 저방법 구글링해서 써봤는데 ... ㅠ_ㅜ </td>\r\n");
      out.write("                  <td>DB</td>\r\n");
      out.write("                  <td>7/3</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">1</th>\r\n");
      out.write("                  <td>JAVA 어느정도가 신입의 기준인가요?</td>\r\n");
      out.write("                  <td>DB</td>\r\n");
      out.write("                  <td>7/3</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            <br>\r\n");
      out.write("            <h3><small># NEW</small></h3>\r\n");
      out.write("            <table class=\"table table-sm table-hover\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"col\">No</th>\r\n");
      out.write("                  <th scope=\"col\">질문</th>\r\n");
      out.write("                  <th scope=\"col\">분야</th>\r\n");
      out.write("                  <th scope=\"col\">조회수/댓글수</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">5</th>\r\n");
      out.write("                  <td>고수님들 쫌 도와주세요.</td>\r\n");
      out.write("                  <td>JAVA</td>\r\n");
      out.write("                  <td>10/0</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">4</th>\r\n");
      out.write("                  <td>고수님들 쫌 도와주세요.</td>\r\n");
      out.write("                  <td>JAVA</td>\r\n");
      out.write("                  <td>10/0</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">3</th>\r\n");
      out.write("                  <td>고수님들 쫌 도와주세요.</td>\r\n");
      out.write("                  <td>JAVA</td>\r\n");
      out.write("                  <td>10/0</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">2</th>\r\n");
      out.write("                  <td>이 에러는 왜 날까요? 이방법 저방법 구글링해서 써봤는데 ... ㅠ_ㅜ </td>\r\n");
      out.write("                  <td>DB</td>\r\n");
      out.write("                  <td>7/3</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th scope=\"row\">1</th>\r\n");
      out.write("                  <td>JAVA 어느정도가 신입의 기준인가요?</td>\r\n");
      out.write("                  <td>DB</td>\r\n");
      out.write("                  <td>7/3</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"tab-pane\" id=\"course\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-header card-header-text card-header-primary\">\r\n");
      out.write("                      <div class=\"card-text\">\r\n");
      out.write("                        <h4 class=\"card-title\">과정명</h4>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <h5><b>사용언어#</h5></b>\r\n");
      out.write("                      상세설명 쓰는란\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                  <div class=\"card\">\r\n");
      out.write("                      <div class=\"card-header card-header-text card-header-primary\">\r\n");
      out.write("                        <div class=\"card-text\">\r\n");
      out.write("                          <h4 class=\"card-title\">과정명</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"card-body\">\r\n");
      out.write("                        <h5><b>사용언어#</h5></b>\r\n");
      out.write("                        상세설명 쓰는란\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-header card-header-text card-header-primary\">\r\n");
      out.write("                      <div class=\"card-text\">\r\n");
      out.write("                        <h4 class=\"card-title\">과정명</h4>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <h5><b>사용언어#</h5></b>\r\n");
      out.write("                      상세설명 쓰는란\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            \r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                  <div class=\"card\">\r\n");
      out.write("                      <div class=\"card-header card-header-text card-header-primary\">\r\n");
      out.write("                        <div class=\"card-text\">\r\n");
      out.write("                          <h4 class=\"card-title\">과정명</h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"card-body\">\r\n");
      out.write("                        <h5><b>사용언어#</h5></b>\r\n");
      out.write("                        상세설명 쓰는란\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 8월26일 재만 수정끝-->\r\n");
      out.write("            <div class=\"text-right\">\r\n");
      out.write("              <a href=\"base.html\" class=\"btn btn-primary btn-sm\">더보기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--  End Modal -->\r\n");
      out.write("  <footer class=\"footer\" data-background-color=\"black\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <nav class=\"float-left\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"https://www.creative-tim.com/license\">\r\n");
      out.write("             \t 사이트 관련 문의\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <div class=\"copyright float-right\">\r\n");
      out.write("        &copy;\r\n");
      out.write("        <script>\r\n");
      out.write("          document.write(new Date().getFullYear())\r\n");
      out.write("        </script>, made with <i class=\"material-icons\">favorite</i> by\r\n");
      out.write("        <a href=\"https://www.creative-tim.com/\" target=\"_blank\">Magpies</a> for a better web.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!--   Core JS Files   -->\r\n");
      out.write("  <script src=\"/resources/assets_home/js/core/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"/resources/assets_home/js/core/popper.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"/resources/assets_home/js/core/bootstrap-material-design.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"/resources/assets_home/js/plugins/moment.min.js\"></script>\r\n");
      out.write("  <!--\tPlugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->\r\n");
      out.write("  <script src=\"/resources/assets_home/js/plugins/bootstrap-datetimepicker.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->\r\n");
      out.write("  <script src=\"/resources/assets_home/js/plugins/nouislider.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <!--  Google Maps Plugin    -->\r\n");
      out.write("  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->\r\n");
      out.write("  <script src=\"/resources/assets_home/js/material-kit.js?v=2.0.7\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      //init DateTimePickers\r\n");
      out.write("      materialKit.initFormExtendedDatetimepickers();\r\n");
      out.write("\r\n");
      out.write("      // Sliders Init\r\n");
      out.write("      materialKit.initSliders();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function scrollToDownload() {\r\n");
      out.write("      if ($('.section-download').length != 0) {\r\n");
      out.write("        $(\"html, body\").animate({\r\n");
      out.write("          scrollTop: $('.section-download').offset().top\r\n");
      out.write("        }, 1000);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
