/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2020-09-21 06:03:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/./include/footer.jsp", Long.valueOf(1600322969878L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1598927620350L));
    _jspx_dependants.put("jar:file:/D:/Git_repositories/lms_system/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LMS_PROJECT/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\" />\n");
      out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"./assets/img/apple-icon.png\">\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"./assets/img/favicon.png\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("  <title>\n");
      out.write("     weLEarn - 배우고 ! 익히고 !\n");
      out.write("  </title>\n");
      out.write("  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />\n");
      out.write("  <!--     Fonts and icons     -->\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css\">\n");
      out.write("  <!-- CSS Files -->\n");
      out.write("  <link href=\"/resources/assets_home/css/material-kit.css?v=2.0.7\" rel=\"stylesheet\" />\n");
      out.write("  <!-- CSS Just for demo purpose, don't include it in your project -->\n");
      out.write("  <link href=\"/resources/assets_home/demo/demo.css\" rel=\"stylesheet\" />\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("    hr.line {\n");
      out.write("      border-top: 1px solid rgb(182, 181, 181);\n");
      out.write("    }    \n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"profile-page sidebar-collapse\">\n");
      out.write("  <!-- 로그인 폼 -->\n");
      out.write("  <div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"\">\n");
      out.write("    <div class=\"modal-dialog modal-login\" role=\"document\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"card card-signup card-plain\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <div class=\"card-header card-header-primary text-center\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><i class=\"material-icons\">clear</i></button>\n");
      out.write("                        <br>\n");
      out.write("                        <h4 class=\"card-title\">Log in</h3>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <form class=\"form\" method=\"post\" action=\"/member/login\">\n");
      out.write("                  <div class=\"modal-body\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                      <div class=\"form-group bmd-form-group\">\n");
      out.write("                          <div class=\"input-group\">\n");
      out.write("                              <span class=\"input-group-addon\">\n");
      out.write("                                  <i class=\"material-icons\">face</i>\n");
      out.write("                              </span>\n");
      out.write("                              <input name=\"id\" type=\"text\" class=\"form-control\" placeholder=\" 아이디 입력\">\n");
      out.write("                          </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"form-group bmd-form-group\">\n");
      out.write("                          <div class=\"input-group\">\n");
      out.write("                              <span class=\"input-group-addon\">\n");
      out.write("                                  <i class=\"material-icons\">lock_outline</i>\n");
      out.write("                              </span>\n");
      out.write("                              <input name=\"password\" type=\"password\" placeholder=\"비밀번호 입력\" class=\"form-control\">\n");
      out.write("                          </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"modal-footer justify-content-center\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary btn-link btn-wd btn-lg\">로그인</button>\n");
      out.write("                  </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("<!--8.25재만수정끝-->\n");
      out.write("\n");
      out.write("  <!--상단 네비게이션 바-->\n");
      out.write("  <nav class=\"navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg bg-primary\" color-on-scroll=\"100\" id=\"sectionsNav\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("      <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("      </button>\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\n");
      out.write("        <!-- 아이콘 바 -->\n");
      out.write("        <ul class=\"navbar-nav ml-auto\" role=\"tablist\">\n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("          <li class=\"nav-item dropdown\">\n");
      out.write("            <a class=\"nav-link dropdown-toggle\" href=\"javascript:;\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("              <i class=\"material-icons\">face</i>&nbsp;&nbsp; \n");
      out.write("              ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("              ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            </a>\n");
      out.write("            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\n");
      out.write("              ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("              ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  <!-- 상단 로고  main header -->\n");
      out.write("  <div class=\"page-header header-filter clear-filter purple-filter\" data-parallax=\"true\" style=\"background-image: url('/resources/assets_home/img/main/bg-main.png');\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-10 ml-auto mr-auto\">\n");
      out.write("          <div class=\"brand\">\n");
      out.write("            <div class=\"col-sm-4\">\n");
      out.write("              <img class=\"img-fluid\" src=\"/resources/assets_home/img/main/logo-dark.png\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div class=\"main main-raised\">\n");
      out.write("    <div class=\"section section-basic\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("      \t<!-- 아이콘 바 -->\n");
      out.write("      \t<div class=\"row\">\n");
      out.write("\t       <div class=\"col-md-12 d-flex justify-content-center\">\n");
      out.write("\t\t        <ul class=\"nav nav-pills nav-pills-icons\" role=\"tablist\">\n");
      out.write("\t\t          <li class=\"nav-item\">\n");
      out.write("\t\t              <a class=\"nav-link active\" href=\"#welearn\" role=\"tab\" data-toggle=\"tab\">\n");
      out.write("\t\t                  <i class=\"material-icons\">emoji_people</i>\n");
      out.write("\t\t                  weLEarn\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t          </li>\n");
      out.write("\t\t          <li class=\"nav-item\">\n");
      out.write("\t\t            <a class=\"nav-link\" href=\"#learn\" role=\"tab\" data-toggle=\"tab\">\n");
      out.write("\t\t                <i class=\"material-icons\">edit</i>\n");
      out.write("\t\t                학습하기\n");
      out.write("\t\t            </a>\n");
      out.write("\t\t          </li>\n");
      out.write("\t\t          <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"#review\" role=\"tab\" data-toggle=\"tab\">\n");
      out.write("                  <i class=\"material-icons\">psychology</i>\n");
      out.write("\t\t              복습하기\n");
      out.write("                </a>\n");
      out.write("\t\t          </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"#question\" role=\"tab\" data-toggle=\"tab\">\n");
      out.write("                    <i class=\"material-icons\">rate_review</i>\n");
      out.write("                    모의고사\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("\t\t          <li class=\"nav-item\">\n");
      out.write("\t\t              <a class=\"nav-link\" href=\"#dashboard\" role=\"tab\" data-toggle=\"tab\">\n");
      out.write("\t\t                  <i class=\"material-icons\">dashboard</i>\n");
      out.write("\t\t                  학습현황\n");
      out.write("\t\t              </a>\n");
      out.write("\t\t          </li>\n");
      out.write("\t\t        </ul>\n");
      out.write("       \t\t</div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- 아이콘 클릭시 !! -->\n");
      out.write("        <div class=\"tab-content tab-space\">\n");
      out.write("        \n");
      out.write("          <!--- 소개 welearn ------------------------------>\n");
      out.write("          <div class=\"tab-pane active\" id=\"welearn\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("              <div class=\"col-md-10 mr-auto ml-auto\">\n");
      out.write("                <hr class=\"line\">\n");
      out.write("                <div class=\"row d-flex align-items-center\">\n");
      out.write("                  <div class=\"col-sm-5 d-flex justify-content-center\">\n");
      out.write("                    <div class=\"col-sm-10\">\n");
      out.write("                      <img class=\"img-fluid \" src=\"/resources/assets_home/img/main/logo-dark.png\">\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"col-sm-6 rounded\">\n");
      out.write("                    <br>\n");
      out.write("                    <table class=\"table table-borderless\">\n");
      out.write("                      <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                          <td><button class=\"btn btn-danger btn-sm\">&nbsp;&nbsp; We &nbsp;&nbsp;</button></td>\n");
      out.write("                          <td>\n");
      out.write("                            <p class=\"text-danger\">\n");
      out.write("                            '우리'라는 가치 추구\n");
      out.write("                            </p>\n");
      out.write("                          </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td><button class=\"btn btn-primary btn-sm\">Learn </button></td>\n");
      out.write("                          <td>\n");
      out.write("                            <p class=\"text-primary\">\n");
      out.write("                              '배움'의 본연 가치 실현\n");
      out.write("                            </p>\n");
      out.write("                          </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td><button class=\"btn btn-success btn-sm\">&nbsp; Well&nbsp;</button></td>\n");
      out.write("                          <td>\n");
      out.write("                            <p class=\"text-success\">\n");
      out.write("                              '잘' 배울 수 있도록 학습 추천\n");
      out.write("                            </p>\n");
      out.write("                          </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td><button class=\"btn btn-info btn-sm\">&nbsp; Earn&nbsp;</button></td>\n");
      out.write("                          <td>\n");
      out.write("                            <p class=\"text-info\">\n");
      out.write("                              '얻어'가는 학습 효과\n");
      out.write("                            </p>\n");
      out.write("                          </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td></td>\n");
      out.write("                          <td></td>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <hr class=\"line\">\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write(" \t\t      <!--- 학습하기 learn ------------------------------>\n");
      out.write("          <div class=\"tab-pane\" id=\"learn\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("              <div class=\"col-md-8 mr-auto ml-auto\">\n");
      out.write("                <!-- Carousel Card -->\n");
      out.write("                <div class=\"card card-raised card-carousel\">\n");
      out.write("                  <div id=\"carousel_study\" class=\"carousel slide\" data-ride=\"carousel\" data-interval=\"10000\">\n");
      out.write("                    <ol class=\"carousel-indicators\">\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"3\"></li>\n");
      out.write("                    </ol>\n");
      out.write("                    <div class=\"carousel-inner\">\n");
      out.write("                      <div class=\"carousel-item active\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/study1.gif\" alt=\"학습 신청\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                            학습 신청\n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/study2.gif\" alt=\"학습 계획 작성\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                            학습 계획 작성\n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/study3.jpg\" alt=\"내 학습\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                            내 학습\n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/study4.gif\" alt=\"학습 스터디룸 \">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                            학습 스터디룸 \n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <a class=\"carousel-control-prev\" href=\"#carousel_study\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                      <i class=\"material-icons\">keyboard_arrow_left</i>\n");
      out.write("                      <span class=\"sr-only\">Previous</span>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"carousel-control-next\" href=\"#carousel_study\" role=\"button\" data-slide=\"next\">\n");
      out.write("                      <i class=\"material-icons\">keyboard_arrow_right</i>\n");
      out.write("                      <span class=\"sr-only\">Next</span>\n");
      out.write("                    </a>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- End Carousel Card -->\n");
      out.write("              </div>\n");
      out.write("            </div>   \n");
      out.write("          </div>\n");
      out.write("\n");
      out.write(" \t\t      <!--- 복습하기 review ------------------------------>\n");
      out.write("          <div class=\"tab-pane\" id=\"review\">\n");
      out.write("\t          <div class=\"container\">\n");
      out.write("\t            <div class=\"col-md-8 mr-auto ml-auto\">\n");
      out.write("          \t\t<!-- Carousel Card -->\n");
      out.write("                <div class=\"card card-raised card-carousel\">\n");
      out.write("                  <div id=\"carousel_review\" class=\"carousel slide\" data-ride=\"carousel\" data-interval=\"10000\">\n");
      out.write("                    <ol class=\"carousel-indicators\">\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\n");
      out.write("                    </ol>\n");
      out.write("                    <div class=\"carousel-inner\">\n");
      out.write("                      <div class=\"carousel-item active\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/review1.gif\" alt=\"학습 신청\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                            복습 추천\n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/review2.gif\" alt=\"학습 계획 작성\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                             복습 하기\n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <a class=\"carousel-control-prev\" href=\"#carousel_review\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                      <i class=\"material-icons\">keyboard_arrow_left</i>\n");
      out.write("                      <span class=\"sr-only\">Previous</span>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"carousel-control-next\" href=\"#carousel_review\" role=\"button\" data-slide=\"next\">\n");
      out.write("                      <i class=\"material-icons\">keyboard_arrow_right</i>\n");
      out.write("                      <span class=\"sr-only\">Next</span>\n");
      out.write("                    </a>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- End Carousel Card -->\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            \n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write(" \t\t      <!--- 문제풀기 question ------------------------------>\n");
      out.write("          <div class=\"tab-pane\" id=\"question\">\n");
      out.write("           <div class=\"container\">\n");
      out.write("\t            <div class=\"col-md-8 mr-auto ml-auto\">\n");
      out.write("          \t\t<!-- Carousel Card -->\n");
      out.write("                <div class=\"card card-raised card-carousel\">\n");
      out.write("                  <div id=\"carousel_testing\" class=\"carousel slide\" data-ride=\"carousel\" data-interval=\"10000\">\n");
      out.write("                    <ol class=\"carousel-indicators\">\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\n");
      out.write("                    </ol>\n");
      out.write("                    <div class=\"carousel-inner\">\n");
      out.write("                      <div class=\"carousel-item active\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/test1.gif\" alt=\"학습 신청\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                          \t  모의시작\n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/test2.gif\" alt=\"학습 계획 작성\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                              모의 고사 결과 확인                      \n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <a class=\"carousel-control-prev\" href=\"#carousel_testing\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                      <i class=\"material-icons\">keyboard_arrow_left</i>\n");
      out.write("                      <span class=\"sr-only\">Previous</span>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"carousel-control-next\" href=\"#carousel_testing\" role=\"button\" data-slide=\"next\">\n");
      out.write("                      <i class=\"material-icons\">keyboard_arrow_right</i>\n");
      out.write("                      <span class=\"sr-only\">Next</span>\n");
      out.write("                    </a>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- End Carousel Card -->\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("        \n");
      out.write("          <!--- 학습 현황 dashboard ------------------------------>\n");
      out.write("          <div class=\"tab-pane\" id=\"dashboard\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("\t            <div class=\"col-md-8 mr-auto ml-auto\">\n");
      out.write("          \t\t<!-- Carousel Card -->\n");
      out.write("                <div class=\"card card-raised card-carousel\">\n");
      out.write("                  <div id=\"carousel_dashboard\" class=\"carousel slide\" data-ride=\"carousel\" data-interval=\"10000\">\n");
      out.write("                    <ol class=\"carousel-indicators\">\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\n");
      out.write("                      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\n");
      out.write("                    </ol>\n");
      out.write("                    <div class=\"carousel-inner\">\n");
      out.write("                      <div class=\"carousel-item active\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/dashboard1.jpg\" alt=\"학습 신청\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                          \t기억률 변화\n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/dashboard2.jpg\" alt=\"학습 계획 작성\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                             \t   일주일 학습 현황                \n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"carousel-item\">\n");
      out.write("                        <img class=\"d-block w-100\" src=\"/resources/assets_home/img/main/dashboard3.jpg\" alt=\"학습 계획 작성\">\n");
      out.write("                        <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                          <h4>\n");
      out.write("                             \t성실도 \n");
      out.write("                          </h4>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <a class=\"carousel-control-prev\" href=\"#carousel_dashboard\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                      <i class=\"material-icons\">keyboard_arrow_left</i>\n");
      out.write("                      <span class=\"sr-only\">Previous</span>\n");
      out.write("                    </a>\n");
      out.write("                    <a class=\"carousel-control-next\" href=\"#carousel_dashboard\" role=\"button\" data-slide=\"next\">\n");
      out.write("                      <i class=\"material-icons\">keyboard_arrow_right</i>\n");
      out.write("                      <span class=\"sr-only\">Next</span>\n");
      out.write("                    </a>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- End Carousel Card -->\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("          \n");
      out.write("           \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <!--  End Modal -->\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer\" data-background-color=\"black\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <nav class=\"float-left\">\r\n");
      out.write("        <ul>\r\n");
      out.write("       \t  <li>\r\n");
      out.write("            <a href=\"/home\">\r\n");
      out.write("             \t Home\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"/admin\">\r\n");
      out.write("             \t Manager\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <div class=\"copyright float-right\">\r\n");
      out.write("        &copy;\r\n");
      out.write("        <script>\r\n");
      out.write("          document.write(new Date().getFullYear())\r\n");
      out.write("        </script>, made with <i class=\"material-icons\">favorite</i> by\r\n");
      out.write("        <a href=\"https://www.creative-tim.com/\" target=\"_blank\">잇플</a> for a better learn.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>");
      out.write("\n");
      out.write("  <!--   Core JS Files   -->\n");
      out.write("  <script src=\"/resources/assets_home/js/core/jquery.min.js\" type=\"text/javascript\"></script>\n");
      out.write("  <script src=\"/resources/assets_home/js/core/popper.min.js\" type=\"text/javascript\"></script>\n");
      out.write("  <script src=\"/resources/assets_home/js/core/bootstrap-material-design.min.js\" type=\"text/javascript\"></script>\n");
      out.write("  <script src=\"/resources/assets_home/js/plugins/moment.min.js\"></script>\n");
      out.write("  <!--\tPlugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->\n");
      out.write("  <script src=\"/resources/assets_home/js/plugins/bootstrap-datetimepicker.js\" type=\"text/javascript\"></script>\n");
      out.write("  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->\n");
      out.write("  <script src=\"/resources/assets_home/js/plugins/nouislider.min.js\" type=\"text/javascript\"></script>\n");
      out.write("  <!--  Google Maps Plugin    -->\n");
      out.write("  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->\n");
      out.write("  <script src=\"/resources/assets_home/js/material-kit.js?v=2.0.7\" type=\"text/javascript\"></script>\n");
      out.write("  <script>\n");
      out.write("    $(document).ready(function() {\n");
      out.write("      //init DateTimePickers\n");
      out.write("      materialKit.initFormExtendedDatetimepickers();\n");
      out.write("\n");
      out.write("      // Sliders Init\n");
      out.write("      materialKit.initSliders();\n");
      out.write("    });\n");
      out.write("\n");
      out.write("\n");
      out.write("    function scrollToDownload() {\n");
      out.write("      if ($('.section-download').length != 0) {\n");
      out.write("        $(\"html, body\").animate({\n");
      out.write("          scrollTop: $('.section-download').offset().top\n");
      out.write("        }, 1000);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(83,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("          <li class=\"nav-item dropdown\">\n");
          out.write("            <a class=\"nav-link dropdown-toggle\" href=\"javascript:;\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
          out.write("              <i class=\"material-icons\">person_pin</i>&nbsp;&nbsp; STUDY\n");
          out.write("            </a>\n");
          out.write("            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\n");
          out.write("              <a class=\"dropdown-item\" href=\"/user/study\">\n");
          out.write("                <i class=\"material-icons\">edit</i>&nbsp;&nbsp;학습하기\n");
          out.write("              </a>\n");
          out.write("              <a class=\"dropdown-item\" href=\"/user/review\">\n");
          out.write("                <i class=\"material-icons\">psychology</i>&nbsp;&nbsp;복습하기\n");
          out.write("              </a>\n");
          out.write("              <a class=\"dropdown-item\" href=\"/user/testing\">\n");
          out.write("                <i class=\"material-icons\">rate_review</i>&nbsp;&nbsp;모의고사\n");
          out.write("              </a>\n");
          out.write("              <a class=\"dropdown-item\" href=\"/user/status\">\n");
          out.write("                <i class=\"material-icons\">dashboard</i>&nbsp;&nbsp;학습현황\n");
          out.write("              </a>\n");
          out.write("            </div>\n");
          out.write("          </li>\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(107,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" Start ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/home.jsp(108,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 접속 중 ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/home.jsp(111,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("              <a class=\"dropdown-item\" href=\"/member/logout\">로그아웃</a>\n");
          out.write("              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/home.jsp(114,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("              <a class=\"dropdown-item\" data-toggle=\"modal\" data-target=\"#loginModal\">로그인</a>\n");
          out.write("              <a class=\"dropdown-item\" href=\"/member/joinform\">회원가입</a>\n");
          out.write("              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
